//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangSchool.bd
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Controls;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ClientServices = new HashSet<ClientService>();
            this.ServicePhotoes = new HashSet<ServicePhoto>();
        }

        public int idServices { get; set; }
        public string Title { get; set; }
        public decimal Cost { get; set; }
        public int DurationInSeconds { get; set; }
        public string Description { get; set; }
        public Nullable<int> Discount { get; set; }
        public string PhotoPath { get; set; }
        public byte[] Photo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> ServicePhotoes { get; set; }

        public int endCost
        {
            get
            {
                int cost = Convert.ToInt32(Cost);
                int discount = Convert.ToInt32(Discount);
                if (discount == 0)
                {
                    return cost;
                }
                else
                {
                    int result = (cost * discount) / 100;
                    result = cost - result;
                    return result;
                }
            }
        }
    }
}
